window.APP_LANGUAGES = {
  ru: {
    "brand.name": "Груз в Рейс",
    "brand.subtitle": "логистическая платформа",
    "nav.home": "Главная",
    "nav.orders": "Заявки",
    "nav.carriers": "Перевозчики",
    "nav.documents": "Документы",
    "support.title": "Диспетчер онлайн",
    "support.subtitle": "Ответ обычно за 3 минуты",
    "topbar.search": "Найти заявку, перевозчика или документ",
    "topbar.notifications": "Уведомления",
    "actions.placeOrder": "Разместить заявку",
    "actions.login": "Войти в кабинет",
    "home.kicker": "Платформа для грузовладельцев",
    "home.title": "Размещайте грузы, выбирайте перевозчиков и держите документы под рукой",
    "home.copy": "Груз в Рейс помогает быстро создать заявку, получить отклики перевозчиков, проверить документы и не терять историю рейсов.",
    "home.liveSearch": "Подбор машин",
    "home.routeExample": "Москва - Казань",
    "home.routeDetails": "3 отклика · ставка от 78 400 ₽",
    "home.metric1": "перевозчиков в базе",
    "home.metric2": "до первого отклика",
    "home.metric3": "для заявок и документов",
    "home.workflowKicker": "Как работает сервис",
    "home.workflowTitle": "От заявки до закрывающих документов",
    "home.step1Title": "Заполните маршрут",
    "home.step1Copy": "Укажите точку А, точку Б, груз, вес, объем и дату погрузки.",
    "home.step2Title": "Получите отклики",
    "home.step2Copy": "Сравните перевозчиков по ставке, рейтингу, документам и типу транспорта.",
    "home.step3Title": "Закройте рейс",
    "home.step3Copy": "Загрузите договоры, ИНН, акты и быстро найдите их по фильтру.",
    "orders.kicker": "Заявки",
    "orders.title": "Рейсы и отклики перевозчиков",
    "orders.colRoute": "Маршрут",
    "orders.colCargo": "Груз",
    "orders.colVehicle": "Кузов",
    "orders.colPrice": "Ставка",
    "orders.colStatus": "Статус",
    "orders.colUser": "Пользователь",
    "orders.colVerification": "Верификация",
    "orders.statusResponses": "Есть отклики",
    "orders.statusChecking": "Проверка",
    "orders.statusDraft": "Черновик",
    "filters.search": "Поиск",
    "filters.searchPlaceholder": "Маршрут, груз, номер",
    "filters.status": "Статус",
    "filters.vehicle": "Кузов",
    "filters.all": "Все",
    "filters.fromDate": "Дата от",
    "filters.toDate": "Дата до",
    "filters.minPrice": "Ставка от",
    "filters.maxPrice": "Ставка до",
    "filters.reset": "Сбросить",
    "vehicle.tent": "Тент",
    "vehicle.ref": "Рефрижератор",
    "vehicle.gazelle": "Газель",
    "carriers.kicker": "Перевозчики",
    "carriers.title": "Перевозчики",
    "carriers.invite": "Пригласить перевозчика",
    "documents.kicker": "Документы",
    "documents.title": "Хранилище ИНН, договоров и закрывающих",
    "documents.uploadTitle": "Загрузить документы",
    "documents.uploadCopy": "ИНН, договоры, заявки, акты, страховки и доверенности.",
    "documents.chooseFiles": "Выбрать файлы",
    "documents.searchPlaceholder": "Найти документ, ИНН, контрагента",
    "documents.contract": "Договор",
    "documents.act": "Акт",
    "documents.insurance": "Страховка",
    "auth.login": "Войти",
    "auth.register": "Регистрация",
    "auth.noPassword": "Без пароля",
    "auth.name": "Имя",
    "auth.role": "Роль",
    "auth.shipper": "Грузовладелец",
    "auth.carrier": "Перевозчик",
    "auth.dispatcher": "Логист",
    "auth.company": "Компания",
    "auth.phone": "Номер телефона",
    "auth.channel": "Куда отправить подтверждение",
    "auth.consent": "Согласие на обработку персональных данных",
    "auth.getCode": "Получить код",
    "auth.code": "Код подтверждения",
    "auth.confirmCode": "Подтвердить код",
    "auth.confirmTelegram": "Подтвердить в Telegram",
    "auth.changePhone": "Изменить номер",
    "auth.loginTitle": "Вход по номеру телефона",
    "auth.registerTitle": "Регистрация по номеру телефона",
    "auth.loginSubtitle": "Получите одноразовый код в SMS или подтвердите вход через Telegram.",
    "auth.registerSubtitle": "Создайте профиль и подтвердите номер через SMS или Telegram.",
    "auth.profile": "Профиль",
    "auth.inCabinet": "В кабинете",
    "auth.guest": "Гость",
    "auth.guestSubtitle": "Войдите, чтобы сохранять маршруты",
    "auth.verified": "номер подтвержден",
    "profile.kicker": "Профиль",
    "profile.title": "Данные аккаунта",
    "profile.subtitle": "Проверьте данные компании и статус верификации перед размещением заявок.",
    "profile.verifiedTitle": "Телефон подтвержден",
    "profile.notVerifiedTitle": "Телефон не подтвержден",
    "profile.verifiedBy": "Подтверждено через",
    "profile.notVerifiedDetails": "Пройдите SMS или Telegram подтверждение",
    "profile.verifiedStatus": "Проверен",
    "profile.notVerifiedStatus": "Не проверен",
    "profile.save": "Сохранить изменения",
    "profile.saved": "Профиль обновлен",
    "profile.companyInn": "ИНН компании",
    "profile.companyKicker": "Компания",
    "profile.companyUsers": "Пользователи компании",
    "profile.companyVerifiedTitle": "Компания проверена",
    "profile.companyNotVerifiedTitle": "Компания не проверена",
    "profile.companyVerifiedDetails": "Проверка со стороны сайта пройдена",
    "profile.companyNotVerifiedDetails": "Загрузите ИНН и договор для проверки",
    "profile.companyVerifiedStatus": "Проверена",
    "profile.companyNotVerifiedStatus": "Не проверена",
    "profile.userNamePlaceholder": "Имя сотрудника",
    "profile.userPhonePlaceholder": "+7 999 000-00-00",
    "profile.userRoleManager": "Менеджер",
    "profile.userRoleLogist": "Логист",
    "profile.userRoleAccountant": "Бухгалтер",
    "profile.addUser": "Добавить",
    "profile.noUsers": "Пользователей пока нет",
    "profile.noUsersHint": "Добавьте сотрудников, которые принадлежат вашей компании",
    "profile.userAdded": "Пользователь компании добавлен",
    "request.title": "Новая заявка на перевозку",
    "request.subtitle": "Шаблон для груза, точки А и точки Б",
    "request.pointA": "Точка А",
    "request.pointB": "Точка Б",
    "request.cargo": "Груз",
    "request.weight": "Вес, кг",
    "request.volume": "Объем, м³",
    "request.submit": "Сохранить шаблон"
  },
  en: {
    "brand.name": "Cargo to Route",
    "brand.subtitle": "logistics platform",
    "nav.home": "Home",
    "nav.orders": "Orders",
    "nav.carriers": "Carriers",
    "nav.documents": "Documents",
    "support.title": "Dispatcher online",
    "support.subtitle": "Usually replies in 3 minutes",
    "topbar.search": "Find an order, carrier, or document",
    "topbar.notifications": "Notifications",
    "actions.placeOrder": "Place order",
    "actions.login": "Open account",
    "home.kicker": "Platform for shippers",
    "home.title": "Post cargo, choose carriers, and keep documents close",
    "home.copy": "Cargo to Route helps create orders, collect carrier responses, check documents, and keep trip history in one place.",
    "home.liveSearch": "Carrier matching",
    "home.routeExample": "Moscow - Kazan",
    "home.routeDetails": "3 responses · rate from 78,400 RUB",
    "home.metric1": "carriers in database",
    "home.metric2": "to first response",
    "home.metric3": "for orders and documents",
    "home.workflowKicker": "How it works",
    "home.workflowTitle": "From order to closing documents",
    "home.step1Title": "Fill the route",
    "home.step1Copy": "Set point A, point B, cargo, weight, volume, and loading date.",
    "home.step2Title": "Get responses",
    "home.step2Copy": "Compare carriers by rate, rating, documents, and vehicle type.",
    "home.step3Title": "Close the trip",
    "home.step3Copy": "Upload contracts, tax IDs, acts, and find them quickly with filters.",
    "orders.kicker": "Orders",
    "orders.title": "Trips and carrier responses",
    "orders.colRoute": "Route",
    "orders.colCargo": "Cargo",
    "orders.colVehicle": "Vehicle",
    "orders.colPrice": "Rate",
    "orders.colStatus": "Status",
    "orders.colUser": "User",
    "orders.colVerification": "Verification",
    "orders.statusResponses": "Responses",
    "orders.statusChecking": "Checking",
    "orders.statusDraft": "Draft",
    "filters.search": "Search",
    "filters.searchPlaceholder": "Route, cargo, number",
    "filters.status": "Status",
    "filters.vehicle": "Vehicle",
    "filters.all": "All",
    "filters.fromDate": "Date from",
    "filters.toDate": "Date to",
    "filters.minPrice": "Rate from",
    "filters.maxPrice": "Rate to",
    "filters.reset": "Reset",
    "vehicle.tent": "Tent",
    "vehicle.ref": "Refrigerated",
    "vehicle.gazelle": "Van",
    "carriers.kicker": "Carriers",
    "carriers.title": "Carriers",
    "carriers.invite": "Invite carrier",
    "documents.kicker": "Documents",
    "documents.title": "Storage for tax IDs, contracts, and closing papers",
    "documents.uploadTitle": "Upload documents",
    "documents.uploadCopy": "Tax IDs, contracts, orders, acts, insurance, and powers of attorney.",
    "documents.chooseFiles": "Choose files",
    "documents.searchPlaceholder": "Find document, tax ID, counterparty",
    "documents.contract": "Contract",
    "documents.act": "Act",
    "documents.insurance": "Insurance",
    "auth.login": "Sign in",
    "auth.register": "Register",
    "auth.noPassword": "No password",
    "auth.name": "Name",
    "auth.role": "Role",
    "auth.shipper": "Shipper",
    "auth.carrier": "Carrier",
    "auth.dispatcher": "Dispatcher",
    "auth.company": "Company",
    "auth.phone": "Phone number",
    "auth.channel": "Where to send verification",
    "auth.consent": "Personal data processing consent",
    "auth.getCode": "Get code",
    "auth.code": "Verification code",
    "auth.confirmCode": "Confirm code",
    "auth.confirmTelegram": "Confirm in Telegram",
    "auth.changePhone": "Change phone",
    "auth.loginTitle": "Phone sign in",
    "auth.registerTitle": "Phone registration",
    "auth.loginSubtitle": "Get a one-time SMS code or confirm sign in via Telegram.",
    "auth.registerSubtitle": "Create a profile and verify your phone via SMS or Telegram.",
    "auth.profile": "Profile",
    "auth.inCabinet": "In account",
    "auth.guest": "Guest",
    "auth.guestSubtitle": "Sign in to save routes",
    "auth.verified": "phone verified",
    "profile.kicker": "Profile",
    "profile.title": "Account details",
    "profile.subtitle": "Check company data and verification status before placing orders.",
    "profile.verifiedTitle": "Phone verified",
    "profile.notVerifiedTitle": "Phone not verified",
    "profile.verifiedBy": "Verified via",
    "profile.notVerifiedDetails": "Complete SMS or Telegram verification",
    "profile.verifiedStatus": "Verified",
    "profile.notVerifiedStatus": "Not verified",
    "profile.save": "Save changes",
    "profile.saved": "Profile updated",
    "profile.companyInn": "Company tax ID",
    "profile.companyKicker": "Company",
    "profile.companyUsers": "Company users",
    "profile.companyVerifiedTitle": "Company verified",
    "profile.companyNotVerifiedTitle": "Company not verified",
    "profile.companyVerifiedDetails": "Site-side verification passed",
    "profile.companyNotVerifiedDetails": "Upload tax ID and contract for verification",
    "profile.companyVerifiedStatus": "Verified",
    "profile.companyNotVerifiedStatus": "Not verified",
    "profile.userNamePlaceholder": "Employee name",
    "profile.userPhonePlaceholder": "+7 999 000-00-00",
    "profile.userRoleManager": "Manager",
    "profile.userRoleLogist": "Logist",
    "profile.userRoleAccountant": "Accountant",
    "profile.addUser": "Add",
    "profile.noUsers": "No users yet",
    "profile.noUsersHint": "Add employees that belong to your company",
    "profile.userAdded": "Company user added",
    "request.title": "New shipping order",
    "request.subtitle": "Template for cargo, point A, and point B",
    "request.pointA": "Point A",
    "request.pointB": "Point B",
    "request.cargo": "Cargo",
    "request.weight": "Weight, kg",
    "request.volume": "Volume, m³",
    "request.submit": "Save template"
  }
};
